services:
  postgres:
    container_name: postgres_dot
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dot_db_password
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_dot
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'

  redis:
    container_name: redis_dot
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - local-network

networks:
  host:
    external: true
  local-network:
    driver: bridge
volumes:
  postgresql:
  postgresql_data:
